services:
  - type: web
    name: flask-service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:10000
    env: python
    envVars:
      - key: FLASK_ENV
        value: production

  - type: web
    name: fastapi-service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    env: python